In [2]:
from pandas import read_csv
import numpy as np
data=read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [3]:
data.head

<bound method NDFrame.head of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

In [5]:
headers=["Sepal Length", "Sepal Width", "Petal Length", "Petal Width", "Species"]

In [12]:
data=read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names= headers)
data

Petel Length  Patel Width  Sepal Length  Sepal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler=StandardScaler()
x=data.iloc[:, :-1 ].values
y=data.iloc[:, 4].values
scaler.fit(x)

StandardScaler()

In [19]:
x = scaler.transform(x)
x

array([[ -8.17157876,  -4.67883554,  -2.90011626,  -3.30213217],
       [ -8.46521181,  -7.35620215,  -2.90011626,  -3.30213217],
       [ -8.75884487,  -6.2852555 ,  -2.93245334,  -3.30213217],
       [ -8.9056614 ,  -6.82072883,  -2.86777917,  -3.30213217],
       [ -8.31839528,  -4.14336221,  -2.90011626,  -3.30213217],
       [ -7.73112917,  -2.53694224,  -2.80310501,  -2.95642933],
       [ -8.9056614 ,  -5.21430886,  -2.90011626,  -3.12928075],
       [ -8.31839528,  -5.21430886,  -2.86777917,  -3.30213217],
       [ -9.19929445,  -7.89167547,  -2.90011626,  -3.30213217],
       [ -8.46521181,  -6.82072883,  -2.86777917,  -3.47498358],
       [ -7.73112917,  -3.60788889,  -2.86777917,  -3.30213217],
       [ -8.61202834,  -5.21430886,  -2.83544209,  -3.30213217],
       [ -8.61202834,  -7.35620215,  -2.90011626,  -3.47498358],
       [ -9.34611098,  -7.35620215,  -2.9971275 ,  -3.47498358],
       [ -7.14386306,  -2.00146892,  -2.96479042,  -3.30213217],
       [ -7.29067959,   0

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [47]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=1 )
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test, y_prediction)
print(cm)
acc=accuracy_score(y_test, y_prediction)
print(acc)

[[18  0  0]
 [ 0 11  0]
 [ 0  3 13]]
0.9333333333333333


In [49]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test, y_prediction)
print(cm)
acc=accuracy_score(y_test, y_prediction)
print(acc)

[[18  0  0]
 [ 0 11  0]
 [ 0  3 13]]
0.9333333333333333


In [51]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=3 )
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)

In [52]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test, y_prediction)
print(cm)
acc=accuracy_score(y_test, y_prediction)
print(acc)

[[18  0  0]
 [ 0 11  0]
 [ 0  3 13]]
0.9333333333333333
