In [1]:
from pandas import read_csv
import numpy as np
data=read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [2]:
data.head

<bound method NDFrame.head of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

In [3]:
headers=["Sepal Length", "Sepal Width", "Petal Length", "Petal Width", "Species"]

In [4]:
data=read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names= headers)
data

Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler=StandardScaler()
x=data.iloc[:, :-1 ].values
y=data.iloc[:, 4].values
scaler.fit(x)

StandardScaler()

In [7]:
x = scaler.transform(x)
x

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=1 )
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test, y_prediction)
print(cm)
acc=accuracy_score(y_test, y_prediction)
print(acc)

[[15  0  0]
 [ 0 12  1]
 [ 0  1 16]]
0.9555555555555556


In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test, y_prediction)
print(cm)
acc=accuracy_score(y_test, y_prediction)
print(acc)

[[15  0  0]
 [ 0 12  1]
 [ 0  1 16]]
0.9555555555555556


In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=3 )
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test, y_prediction)
print(cm)
acc=accuracy_score(y_test, y_prediction)
print(acc)

[[15  0  0]
 [ 0 12  1]
 [ 0  1 16]]
0.9555555555555556


In [16]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
l=[]



In [17]:
for i in range(0,9):
  x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)
  classifier=KNeighborsClassifier(n_neighbors= 5, metric='minkowski', p=1 )
  classifier.fit(x_train, y_train)
  y_prediction = classifier.predict(x_test)
  cm=confusion_matrix(y_test, y_prediction)
  acc=accuracy_score(y_test, y_prediction)
  l.append(acc)

avg=0
sum=0
for i in range(0,9):
  sum+=l[i]
avg=sum/len(l)
print(avg)
  


0.9358024691358025
